### ISSUE TITLE
Duplicate pageIds

### ISSUE THREAD

**Issue by Dragomir-Ivanov** [dunso/pdf-parser#1]
Hello there,
When parsing a pdf, I see duplicate `pageId`s in different pages. Also pages don't seem to be in order.
`pageId` don't seem to be the actual page of the document.

EDIT: Forgot to mention that my document is more than 100 pages long. It seems that the hundreds digit is missing. Maybe updating the `PDF.js` library can help.

**Comment by dunso** [comment]
I have fixed the bug that pageId is incorrect when pdf is longer than 100 pages. Thanks for your issue. 
The pages are not in order. They are parsed randomly and you need to sort by page.
The page number starts from 0 and pageId plus 1 is the actual page number.
Please try again.

**Comment by Dragomir-Ivanov** [comment]
Thanks for the fix @dunso. Unfortunately I had to use other library because of this bug, so my project is already done. However might come back to your lovely library when time comes. Cheers!
