### ISSUE TITLE
Cannot Find Module

### ISSUE THREAD

**Issue by artem-alek** [dunso/pdf-parser#2]
after cloning and then running the test pdf with `node pdf2json` it cannot find module 
```module.js:557
    throw err;
    ^

Error: Cannot find module '/xxx/xxxxxxxl/xxxxx/pdf-parser/pdf2json'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3
```

**Comment by dunso** [comment]
The example is in the file `example/node/pdf2json.js`.
If you are in the root directory, you can use `node example/node/pdf2json` to run the example.
Or you can `cd example/node` and then `node pdf2json`.
Have a good time!
